### ISSUE TITLE
train_transforms kills the kernel

### ISSUE THREAD

**Issue by good-demo** [JunMa11/NeurIPS-CellSeg#2]
train_ds = monai.data.Dataset(data=train_files) is available add transform=train_transforms will kill kernel

**Comment by JunMa11** [comment]
Hi @good-demo ,

We double-checked the code on our server but cannot reproduce this error.

Could you provide more details?

**Comment by good-demo** [comment]
monai.data.Dataset add parameters(transform=train_transforms) will kill the kernel of jupyter notebook.  Can you providde your version of monai and pytorch.

**Comment by JunMa11** [comment]
Hi @good-demo ,

The current code is only tested on the official training dataset. 

> my verification request has been approved. But I can’t access datasets.
We never had this issue for registered teams. If you have registered for the challenge, please reach out to the official email to describe your problem.

**Comment by JunMa11** [comment]
@good-demo 

>  Can you providde your version of monai and pytorch.

here you go:)

```
MONAI version: 0.9
Numpy version: 1.21.2
Pytorch version: 1.10.1
Nibabel version: 3.2.1
scikit-image version: 0.19.2
Pillow version: 9.0.1
Tensorboard version: 2.8.0
gdown version: 4.2.0
TorchVision version: 0.11.2
tqdm version: 4.63.0
psutil version: 5.8.0
pandas version: 1.4.1
einops version: 0.3.2
```

**Comment by good-demo** [comment]
Thanks for your reply!
