### ISSUE TITLE
About compute_ Problems with metric.py

### ISSUE THREAD

**Issue by BelieferQAQ** [JunMa11/NeurIPS-CellSeg#4]
Hello! Excuse me, I'm going to put metric Py is applied to ribfrac data set (rib fracture) to calculate classification indicators. The GT label and PRED label of this dataset are set to 0, 1, 2, 3, 4, 5 (where 0 represents the background, and 1-5 corresponds to 5 fracture types). You can use metric Py calculate F1 score? Thank you very much.

That is, the range of pixel values in label is 0-5

**Comment by JunMa11** [comment]
Hi, 
The metric.py is for cell segmentation. I'm afraid that it cannot be directly used the ribfrac data.

**Comment by BelieferQAQ** [comment]
> 

thank you
