### ISSUE TITLE
Nan loss with Unet baseline model

### ISSUE THREAD

**Issue by mylifeasazucchini** [JunMa11/NeurIPS-CellSeg#5]
Hi,

I keep getting Nan loss at around 40 epochs. Was this something you also experienced ? I haven't changed anything in the code yet and just run everything out of the box. And if not could you tell me what was the learning rate that you might have used then ?

but before the Nan loss I was able to get a model with **Dice loss of 0.6328**.

**Comment by JunMa11** [comment]
Hi @mylifeasazucchini ,

We didn't experience this issue, but we would recommend using the swinuneter, which can obtain better performance than U-Net.

**Comment by good-demo** [comment]
Using the swinunetr baseline I have  the same problem（the loss is nan), but I didn't  find the problem when I use other data.

**Comment by hasukmin12** [comment]
I have same issue

**Comment by mylifeasazucchini** [comment]
@hasukmin12 @good-demo I think it would be good to open a new issue coz according to github rules, I can't reopen issues closed by the author :( so I am not sure he will notice them if you comment on a closed issue. (but also link it back to this issue for context!)

**Comment by JunMa11** [comment]
@mylifeasazucchini @good-demo @hasukmin12  Please make sure that the monai version is 0.9.
