### ISSUE TITLE
Nan loss with baseline model 

### ISSUE THREAD

**Issue by hasukmin12** [JunMa11/NeurIPS-CellSeg#6]
Hi,

I keep getting Nan loss around 20 epochs. I haven't changed anything in the code yet and just run.
it keep happens even if i use other network like swinunetr, unetr.

![image](https://user-images.githubusercontent.com/56622945/193160437-347fbca2-2f0b-44fc-b929-0aa7cb1dcc08.png)

**Comment by JunMa11** [comment]
Please make sure your monai version is 0.9.

**Comment by JunMa11** [comment]
If you are using the old MONAI, please try to remove the data augmentation


https://github.com/JunMa11/NeurIPS-CellSeg/blob/2df1ee5dc26b4ff10202da73ef22d72651e8e5bd/baseline/model_training_3class.py#L128-L148

**Comment by hasukmin12** [comment]
now i'm using monai 0.9.1 but it still happened

**Comment by hasukmin12** [comment]
when i check this problem by below code
![image](https://user-images.githubusercontent.com/56622945/193164258-02708248-7f7f-49b0-903e-c3dcd05e0b12.png)

this error happens
![image](https://user-images.githubusercontent.com/56622945/193164284-3728ddb4-1d72-4922-a0c7-1a7c6922a820.png)

**Comment by hasukmin12** [comment]
I really don't know why, but inputs gets 'nan' around 20 epochs
![image](https://user-images.githubusercontent.com/56622945/193166591-8a106137-d4f9-46d8-843e-d25785936311.png)

**Comment by JunMa11** [comment]
We cannot reproduce your error. 
- please delete the data and re-run the preprocessing.
- Have you tried to remove the data augmentation?

**Comment by JintuZheng** [comment]
I got the same problem as @hasukmin12  says, my envs: torch 1.10/1.11/1.12+cu113, monai 1.0/0.91/0.9,

I have tried some solutions, and one of them can work:

[1] Remove some data augmentations that may make it run

[2] Change the torch version to 1.8 and make sure your monai is 0.9

[3] However, I think the best idea is to use the docker.
